# Generated by Django 4.1.6 on 2023-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('country_code', models.CharField(blank=True, max_length=128, null=True)),
                ('web_code', models.CharField(blank=True, max_length=128, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone_number_length', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'db_table': 'general_country',
                'ordering': ('name',),
            },
        ),
    ]
