# Generated by Django 4.1.6 on 2023-02-22 03:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=258, null=True)),
                ('Descryption', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('general', 'General')], max_length=128)),
            ],
            options={
                'verbose_name': 'notification message',
                'verbose_name_plural': 'notification messages',
                'db_table': 'notifications_notification_message',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('received', 'Received')], default='pending', max_length=128)),
                ('notification_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationmessage')),
            ],
            options={
                'verbose_name': 'user notification',
                'verbose_name_plural': 'user notifications',
                'db_table': 'notifications_user_notification',
                'ordering': ('date_added',),
            },
        ),
    ]
