# Generated by Django 4.1.6 on 2023-02-15 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('is_book_marked', models.BooleanField(default=False)),
                ('is_purchased', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=128)),
                ('Product_id', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'User product',
                'verbose_name_plural': 'User Products',
                'db_table': 'products_user_product',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('rating_count', models.IntegerField(default=0)),
                ('descryption', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=128)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product reviews',
                'db_table': 'products_product_review',
            },
        ),
    ]
