# Generated by Django 4.1.6 on 2023-02-15 09:48

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_userproduct_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='auto_id',
            field=models.PositiveIntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2023, 2, 15, 9, 47, 59, 471327, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 9, 48, 9, 499111, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='auto_id',
            field=models.PositiveIntegerField(db_index=True, default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2023, 2, 15, 9, 48, 24, 872972, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproduct',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 15, 9, 48, 28, 925871, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userproduct',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ordered', 'Ordered'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending', max_length=128),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
